# Generated by Django 4.0.4 on 2022-05-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shortener_delete_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shortener',
            new_name='Link',
        ),
    ]
