# Generated by Django 4.0.4 on 2022-05-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_link_shorten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='shorten',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='link',
            name='delete_slug',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='link',
            name='visits_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
