# Generated by Django 4.0.4 on 2022-05-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_link_options_remove_link_visits_count_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='delete_slug',
        ),
    ]
