# Generated by Django 4.0.4 on 2022-05-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_link_delete_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='delete_slug',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
